openapi: 3.0.0
info:
  title: Treatment Program API
  version: 1.0.0
  description: API for managing treatment programs and activities.
paths:
  /api/treatment-program:
    get:
      summary: Get treatment programs
      description: Fetches and organizes treatment programs from the database.
      responses:
        '200':
          description: Successfully fetched treatment programs
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: object
                    properties:
                      weekday:
                        type: string
                      title:
                        type: string
                      completed:
                        type: boolean
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/create-activity:
    post:
      summary: Create a new activity
      description: Adds a new activity to the treatment program.
      requestBody:
        description: The activity to be created
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                week:
                  type: string
                weekday:
                  type: string
                title:
                  type: string
                completed:
                  type: boolean
              required:
                - week
                - weekday
                - title
      responses:
        '201':
          description: Successfully created activity
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  week:
                    type: string
                  weekday:
                    type: string
                  title:
                    type: string
                  completed:
                    type: boolean
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/profile:
    post:
      summary: Get user profile
      description: Fetches user profile data from the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Successfully fetched user profile
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  email:
                    type: string
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string